/* ============================================================
   Data — Articles, Categories, Stats
   ============================================================ */

const TC = window.TC = {};

TC.categories = [
  { id: 'AI',           label: 'Artificial Intelligence', icon: '🤖', color: '#BF5AF2', count: 3240 },
  { id: 'Programming',  label: 'Programming',             icon: '💻', color: '#0A84FF', count: 2180 },
  { id: 'Cybersecurity',label: 'Cybersecurity',           icon: '🔐', color: '#FF375F', count: 1560 },
  { id: 'Cloud',        label: 'Cloud Computing',         icon: '☁️',  color: '#30D158', count: 1340 },
  { id: 'Hardware',     label: 'Hardware',                icon: '🖥️',  color: '#FF9F0A', count: 980  },
  { id: 'Research',     label: 'Research',                icon: '🔬', color: '#64D2FF', count: 760  },
  { id: 'Startups',     label: 'Startups',                icon: '🚀', color: '#FF6961', count: 1120 },
  { id: 'Open Source',  label: 'Open Source',             icon: '📦', color: '#30D158', count: 890  },
  { id: 'Dev Tools',    label: 'Developer Tools',         icon: '🛠️',  color: '#0A84FF', count: 780  },
];

TC.stats = [
  { icon: '📰', value: 12847, suffix: '',    label: 'Total Articles',   desc: 'Published since launch' },
  { icon: '🏢', value: 4200,  suffix: '+',   label: 'Companies Covered',desc: 'From startups to giants' },
  { icon: '⚙️', value: 890,   suffix: '',    label: 'Technologies',     desc: 'Tracked & indexed' },
  { icon: '📅', value: 365,   suffix: '',    label: 'Days of Coverage', desc: 'Uninterrupted publishing' },
  { icon: '⏱️', value: 52000, suffix: '+',   label: 'Reading Hours',    desc: 'Total content library' },
  { icon: '🌍', value: 94,    suffix: '',    label: 'Countries',        desc: 'Global coverage' },
];

TC.articles = [
  {
    id: 1,
    category: 'AI',
    title: 'OpenAI Releases GPT-5 Turbo with Real-Time Multimodal Reasoning',
    excerpt: 'The latest model achieves state-of-the-art benchmarks across vision, audio, and code generation tasks.',
    body: [
      "OpenAI today announced the release of GPT-5 Turbo, a model designed to bring multimodal reasoning into real-time applications. The system can simultaneously process text, images, audio, and code — analyzing all modalities in a single inference pass.",
      "The company claims GPT-5 Turbo achieves unprecedented scores on the MMLU, HumanEval, and MATH benchmarks, outperforming both previous OpenAI models and competing systems from Anthropic, Google, and Meta.",
      "The release also introduces a new \"streaming context\" architecture, allowing the model to maintain coherent reasoning across very long conversations without performance degradation. Early access users report GPT-5 Turbo completing complex multi-step coding tasks with a success rate above 91%.",
      "<blockquote>We believe this model marks a qualitative shift in what AI systems can accomplish autonomously in open-ended environments. — Sam Altman, CEO, OpenAI</blockquote>",
      "Pricing has been adjusted to $2 per million input tokens and $6 per million output tokens, placing it in direct competition with Anthropic's Claude Opus and Google's Gemini Ultra offerings. API access is available immediately, with consumer-facing integrations rolling out over the next 30 days.",
    ],
    company: 'OpenAI',
    readTime: 4,
    tags: ['GPT-5', 'Multimodal', 'LLM', 'OpenAI'],
  },
  {
    id: 2,
    category: 'Cybersecurity',
    title: 'Critical Zero-Day Vulnerability Discovered in Linux Kernel Network Stack',
    excerpt: 'Security researchers disclose a high-severity RCE exploit affecting kernels 5.15 through 6.8.',
    body: [
      "A critical zero-day vulnerability in the Linux kernel's network stack has been disclosed by security researchers at Trail of Bits. The flaw, tracked as CVE-2026-7281, allows an unauthenticated attacker to achieve remote code execution on any system running kernel versions 5.15 through 6.8.",
      "The vulnerability exists in the TCP socket cleanup path and can be triggered by sending a specially crafted sequence of packets. Exploitation requires no authentication and leaves minimal traces in standard system logs.",
      "The Linux Security Team has issued an emergency patch (6.8.1) and strongly recommends updating affected systems immediately. Major distributions including Ubuntu, Fedora, Debian, and RHEL have already pushed updated packages.",
      "<blockquote>This is among the most severe kernel vulnerabilities we have seen in the past decade. The attack surface is enormous given how many systems run the affected versions. — Thomas Ptacek, Trail of Bits</blockquote>",
      "Cloud providers including AWS, Google Cloud, and Azure have confirmed they are applying patches to their managed infrastructure. Kubernetes administrators should patch node kernels as a priority, as container isolation does not protect against this class of vulnerability.",
    ],
    company: 'Trail of Bits',
    readTime: 5,
    tags: ['CVE-2026-7281', 'Linux', 'RCE', 'Zero-Day'],
  },
  {
    id: 3,
    category: 'Cloud',
    title: 'AWS Announces Lambda Cold Start Elimination with SnapStart for All Runtimes',
    excerpt: 'Amazon extends its SnapStart feature to Node.js, Python, and Go — reducing init times by up to 90%.',
    body: [
      "Amazon Web Services today announced SnapStart for All Runtimes, extending its proven cold-start elimination technology beyond Java to cover Node.js, Python, Go, and .NET Lambda functions.",
      "SnapStart works by taking a snapshot of an initialized Lambda execution environment, allowing subsequent invocations to restore from that snapshot instead of bootstrapping from scratch. The technology eliminates cold starts for the vast majority of function invocations.",
      "In benchmarks provided by AWS, Python Lambda functions that previously experienced 800ms–1.2s cold starts now initialize in under 80ms with SnapStart enabled. Node.js functions see similar improvements, particularly in functions with heavy dependency trees.",
      "The feature is available at no additional cost and can be enabled with a single configuration flag in the Lambda console or via IaC tools including Terraform, CDK, and SAM.",
      "<blockquote>Cold start latency has been the number one friction point developers cite with serverless. SnapStart for All Runtimes eliminates that concern entirely. — VP of Serverless, AWS</blockquote>",
    ],
    company: 'Amazon Web Services',
    readTime: 3,
    tags: ['AWS Lambda', 'Serverless', 'Cold Start', 'Cloud'],
  },
  {
    id: 4,
    category: 'Programming',
    title: 'TypeScript 6.0 Introduces Algebraic Data Types and Pattern Matching',
    excerpt: 'The TypeScript team ships one of the most-requested features in its history: native ADTs and exhaustive match expressions.',
    body: [
      "TypeScript 6.0 has officially shipped, bringing with it two landmark features that have topped the feature request tracker for years: algebraic data types (ADTs) and a native `match` expression with exhaustiveness checking.",
      "The new `variant` keyword allows developers to define tagged union types that the compiler understands structurally, enabling the `match` expression to provide full type narrowing and exhaustiveness guarantees without manual type guards.",
      "Early adopters report that the pattern matching syntax dramatically reduces boilerplate in state machine implementations, parser combinators, and domain modeling scenarios. The compiler error messages for non-exhaustive matches are described as exceptionally helpful.",
      "<blockquote>Pattern matching is the feature I've wanted in TypeScript since 2018. The implementation is clean, composable, and feels native to the language. — Dan Abramov, software engineer</blockquote>",
      "The release also includes significant improvements to inference in conditional types, faster incremental compilation, and a new `strict-readonly` compiler option that prevents accidental mutation of function parameters.",
    ],
    company: 'Microsoft',
    readTime: 5,
    tags: ['TypeScript', 'ADT', 'Pattern Matching', 'Microsoft'],
  },
  {
    id: 5,
    category: 'Hardware',
    title: 'Apple Silicon M4 Ultra Benchmarks Reveal 40% IPC Improvement Over M3',
    excerpt: 'Leaked Geekbench scores and die shots confirm Apple\'s biggest generational CPU jump since M1.',
    body: [
      "Leaked Geekbench 6 scores and high-resolution die shots of Apple's upcoming M4 Ultra chip reveal a generational improvement in single-core performance that surpasses expectations set by analysts earlier this year.",
      "The M4 Ultra achieves a single-core score of 4,820 and a multi-core score of 42,300 in early Geekbench 6 tests — representing a 38–42% IPC improvement over the M3 Ultra at equivalent clock speeds.",
      "The improvement stems from a redesigned core microarchitecture featuring wider issue windows, deeper out-of-order execution buffers, and a new prefetch unit tuned specifically for large language model inference workloads.",
      "Apple is expected to announce the M4 Ultra in Mac Pro and Mac Studio configurations at its annual developer conference. The chip's dedicated Neural Engine scores in leaked benchmarks suggest a 3× improvement in tokens-per-second for on-device LLM inference.",
      "<blockquote>If these numbers hold up, the M4 Ultra will run a 70B parameter model entirely in RAM at speeds competitive with a cloud API. That's a fundamental shift for on-device AI. — Anandtech analysis</blockquote>",
    ],
    company: 'Apple',
    readTime: 4,
    tags: ['Apple Silicon', 'M4 Ultra', 'CPU', 'Hardware'],
  },
  {
    id: 6,
    category: 'Startups',
    title: 'Vercel Raises $250M Series F at $5B Valuation to Fund Edge AI Infrastructure',
    excerpt: 'The frontend cloud platform plans to build AI-powered deployment intelligence at the network edge.',
    body: [
      "Vercel has closed a $250 million Series F funding round at a $5 billion valuation, the company announced today. The round was led by Accel and Sequoia, with participation from existing investors including GV and CRV.",
      "The capital will be directed primarily toward what Vercel calls 'Edge AI Infrastructure' — a new class of deployment tooling that uses machine learning to optimize routing, prefetching, and cache invalidation decisions at the CDN level.",
      "In practice, this means Vercel's network will analyze traffic patterns, user behavior signals, and application usage data to proactively warm edge caches and reduce time-to-first-byte for personalized content without sacrificing cache hit rates.",
      "CEO Guillermo Rauch described the vision as making the entire delivery layer 'intelligent by default' — infrastructure that learns and adapts rather than requiring manual cache-control configuration.",
      "<blockquote>The next decade of web performance will be won at the intelligence layer, not the infrastructure layer. We're building an edge that thinks. — Guillermo Rauch, CEO, Vercel</blockquote>",
    ],
    company: 'Vercel',
    readTime: 4,
    tags: ['Vercel', 'Funding', 'Edge Computing', 'AI Infrastructure'],
  },
  {
    id: 7,
    category: 'Open Source',
    title: 'Linux Foundation Launches Project Granite: Unified Observability Standard',
    excerpt: 'A coalition of 40+ companies backs a new open standard for distributed tracing, metrics, and logs.',
    body: [
      "The Linux Foundation today announced Project Granite, a new initiative to create a unified open standard for cloud-native observability covering distributed tracing, metrics aggregation, and structured logging under a single protocol and wire format.",
      "The project has initial backing from over 40 companies including Google, Microsoft, Datadog, New Relic, Grafana Labs, and HashiCorp. Project Granite builds on the foundations of OpenTelemetry but introduces a standardized query language and a vendor-neutral data plane specification.",
      "The core innovation is the Granite Unified Query Language (GUQL), which allows operators to write a single observability query that executes identically across any GUQL-compliant backend — eliminating lock-in to vendor-specific query dialects like PromQL, LogQL, or NRQL.",
      "A reference implementation in Go is available today under the Apache 2.0 license, with SDK support for Java, Node.js, Python, and Rust planned for Q3 2026.",
      "<blockquote>Operators waste enormous time rewriting observability queries when they switch backends. Granite ends that permanently. — Director of Engineering, Google Cloud Observability</blockquote>",
    ],
    company: 'Linux Foundation',
    readTime: 4,
    tags: ['Open Source', 'Observability', 'OpenTelemetry', 'Linux Foundation'],
  },
  {
    id: 8,
    category: 'Research',
    title: 'DeepMind AlphaCode 3 Achieves Grandmaster-Level Performance on Competitive Programming',
    excerpt: 'The latest AlphaCode model solves 72% of Codeforces Grandmaster-tier problems in a 90-minute contest format.',
    body: [
      "DeepMind's AlphaCode 3 has achieved what the company describes as 'Grandmaster-level' performance on competitive programming challenges, solving 72% of problems from Codeforces contests at the Grandmaster rating tier within a simulated 90-minute window.",
      "Unlike previous AlphaCode versions, AlphaCode 3 generates far fewer candidate solutions and relies on an internal 'solution verifier' that predicts the correctness of a solution before it is submitted — dramatically improving precision and reducing wasted compute.",
      "The model demonstrates particular strength in dynamic programming, graph algorithms, and combinatorics — problem categories where previous AI systems struggled due to the need for non-obvious mathematical insight.",
      "<blockquote>AlphaCode 3 doesn't just pattern-match to similar training examples. It appears to construct novel problem decompositions using techniques we didn't explicitly train for. — Research lead, DeepMind AlphaCode team</blockquote>",
      "The technical report accompanying the release notes the model's performance degrades on problems requiring very recent algorithmic research (published after 2024), highlighting a knowledge cutoff effect that remains an active area of investigation.",
    ],
    company: 'DeepMind',
    readTime: 5,
    tags: ['AlphaCode', 'DeepMind', 'Competitive Programming', 'Research'],
  },
  {
    id: 9,
    category: 'Dev Tools',
    title: 'JetBrains Releases Aqua 2.0: First IDE Built Natively for Test Engineering',
    excerpt: 'Aqua 2.0 ships with integrated test failure analysis, AI-powered assertions, and a visual test runner.',
    body: [
      "JetBrains has released Aqua 2.0, a major update to its test-engineering-focused IDE that introduces AI-powered test failure analysis, automatic assertion generation, and a redesigned visual test runner with live execution graphs.",
      "The centrepiece of the 2.0 release is 'FailSense' — a system that analyzes failing tests, correlates them with recent code changes using semantic diff analysis, and suggests the most likely root cause ranked by confidence score.",
      "Aqua 2.0 also integrates natively with Playwright, Cypress, pytest, JUnit 5, and Vitest, providing dedicated UIs for each framework that surface framework-specific metrics (e.g., Playwright's trace viewer, pytest fixtures graph) without leaving the IDE.",
      "The AI-powered assertion feature can inspect a function's return type and suggest idiomatic assertions, catching common mistakes like comparing reference equality instead of structural equality in object comparisons.",
    ],
    company: 'JetBrains',
    readTime: 3,
    tags: ['JetBrains', 'Aqua', 'Testing', 'IDE'],
  },
  {
    id: 10,
    category: 'AI',
    title: 'Anthropic Publishes Model Spec for Claude: Full Constitutional AI Framework Released',
    excerpt: 'Anthropic open-sources the complete value alignment specification used to train the Claude family of models.',
    body: [
      "Anthropic today published the complete Constitutional AI specification used to train the Claude model family, marking one of the most detailed public disclosures of an AI alignment methodology from a frontier lab.",
      "The specification covers Claude's core values hierarchy, how conflicts between helpfulness, harmlessness, and honesty are resolved, the process for generating and curating the 'constitution' used in RLAIF training, and the evaluation suite used to measure alignment properties.",
      "Particularly notable is the section on 'value extrapolation' — how the system handles situations not covered by explicit training examples by inferring what a thoughtful, senior Anthropic employee would consider appropriate.",
      "The release is accompanied by a 240-page technical paper detailing Constitutional AI v2, including ablation studies demonstrating how different constitutional principles affect model behavior across diverse task categories.",
      "<blockquote>Transparency about alignment methodology is essential for the field to make progress. We hope other labs follow with similar disclosures. — Dario Amodei, CEO, Anthropic</blockquote>",
    ],
    company: 'Anthropic',
    readTime: 6,
    tags: ['Anthropic', 'Claude', 'Alignment', 'Constitutional AI'],
  },
  {
    id: 11,
    category: 'Cloud',
    title: 'Google Cloud Spanner Adds Vector Search — Challenging Pinecone and Weaviate',
    excerpt: 'Cloud Spanner now natively stores and queries vector embeddings at planetary scale without a separate vector DB.',
    body: [
      "Google Cloud has added native vector search capabilities to Cloud Spanner, its globally distributed NewSQL database, enabling developers to store, index, and query high-dimensional embeddings directly alongside transactional data — without a separate vector database.",
      "The implementation supports approximate nearest-neighbor (ANN) search using Google's ScaNN algorithm, with configurable accuracy/recall tradeoffs and automatic index management. Vectors of up to 8,192 dimensions are supported.",
      "By integrating vector search into Spanner, Google addresses a significant architectural pain point in AI applications: maintaining consistency between a primary database and a separate vector store requires complex synchronization logic that is a common source of bugs and latency.",
      "<blockquote>Every AI application we build eventually needs to reconcile its vector index with its source-of-truth database. Spanner with native vectors eliminates that problem entirely. — Staff Engineer, Google</blockquote>",
      "Pricing for vector index storage and query operations is integrated into Spanner's existing unit pricing, making the total cost competitive with standalone vector database offerings for high-throughput workloads.",
    ],
    company: 'Google Cloud',
    readTime: 4,
    tags: ['Google Cloud', 'Spanner', 'Vector Search', 'AI Infrastructure'],
  },
  {
    id: 12,
    category: 'Cybersecurity',
    title: 'Signal Upgrades Protocol to Resist Quantum Decryption with NIST PQC Standards',
    excerpt: 'Signal becomes the first major consumer messaging app to deploy post-quantum cryptography end-to-end.',
    body: [
      "Signal has deployed an upgrade to its secure messaging protocol that integrates NIST-standardized post-quantum cryptographic algorithms, making it the first widely-used consumer messaging application to offer quantum-resistant end-to-end encryption.",
      "The upgrade combines Signal's existing X3DH and Double Ratchet protocols with CRYSTALS-Kyber for key encapsulation and CRYSTALS-Dilithium for digital signatures — the two NIST PQC standards finalized in 2024.",
      "The hybrid approach means communications are secure against both classical and quantum adversaries. Even if a quantum computer capable of breaking current elliptic-curve cryptography were to emerge, intercepted Signal messages would remain undecipherable.",
      "The upgrade is transparent to users — no action is required. All clients running Signal version 8.0 or later automatically negotiate the post-quantum protocol when both parties have updated.",
      "<blockquote>The threat from 'harvest now, decrypt later' attacks is real today. State actors are collecting encrypted traffic now, waiting for quantum capability. We're closing that window. — Meredith Whittaker, President, Signal Foundation</blockquote>",
    ],
    company: 'Signal Foundation',
    readTime: 5,
    tags: ['Signal', 'Post-Quantum', 'Cryptography', 'Privacy'],
  },
  {
    id: 13,
    category: 'Programming',
    title: 'Rust 2.0 Edition Ships with Async Traits Stabilized and Borrow Checker 2.0',
    excerpt: 'The most significant Rust release in years introduces async-in-traits, non-lexical lifetimes 2.0, and a rewritten borrow checker.',
    body: [
      "The Rust project has released the 2.0 Edition, the most significant version since the 2021 Edition, featuring three long-awaited improvements: stabilized async traits, a rewritten borrow checker (NLL 2.0), and ergonomic lifetime elision improvements.",
      "Async traits — the ability to define `async fn` methods directly in trait definitions — has been one of Rust's most requested features for years. The stabilization removes the need for workarounds like the `async_trait` proc macro, simplifying async code dramatically.",
      "The new borrow checker (NLL 2.0) reduces the incidence of false-positive lifetime errors, particularly in patterns involving self-referential structs and complex iterators. Rust team benchmarks show 31% fewer borrow check errors on real-world codebases compared to NLL 1.0.",
      "<blockquote>Rust 2.0 is the version that turns Rust from 'correct but painful' to 'correct and enjoyable.' The async ecosystem can finally unify around a single pattern. — Niko Matsakis, Rust team lead</blockquote>",
    ],
    company: 'Rust Foundation',
    readTime: 5,
    tags: ['Rust', 'Async', 'Programming Languages', 'Systems Programming'],
  },
  {
    id: 14,
    category: 'AI',
    title: 'Meta Open-Sources Llama 4 70B: Outperforms GPT-4o on Key Benchmarks',
    excerpt: 'Meta releases the largest open-weight model to date, with performance rivaling closed-source frontier models.',
    body: [
      "Meta has open-sourced Llama 4 in 8B, 70B, and 405B parameter configurations under a permissive research and commercial license, with the 70B model achieving performance metrics that rival or exceed GPT-4o on several standard benchmarks.",
      "In Meta's published evaluation, Llama 4 70B outperforms GPT-4o on MATH (89.3% vs 87.1%), HumanEval (92.1% vs 90.2%), and MMLU (88.4% vs 87.9%), while matching it closely on reasoning benchmarks like ARC-Challenge.",
      "The model introduces a new mixture-of-experts architecture at the 405B scale, activating only 70B parameters per forward pass while maintaining the knowledge capacity of the full 405B. This makes inference on the largest version practical on 8×H100 configurations.",
      "<blockquote>Open models at frontier performance change the competitive dynamics of AI permanently. Every organization now has access to state-of-the-art capabilities. — Yann LeCun, Chief AI Scientist, Meta</blockquote>",
      "The release is expected to significantly accelerate fine-tuning research and the development of specialized vertical AI applications, as organizations can now customize frontier-quality models on proprietary data without API dependency.",
    ],
    company: 'Meta',
    readTime: 5,
    tags: ['Llama 4', 'Meta', 'Open Source AI', 'LLM'],
  },
  {
    id: 15,
    category: 'Startups',
    title: 'Linear Launches Linear AI: Issue Management with Autonomous Sprint Planning',
    excerpt: 'The popular project management tool adds an AI layer that autonomously decomposes epics, estimates effort, and balances sprints.',
    body: [
      "Linear, the project management tool popular among engineering teams, has launched Linear AI — an integrated AI layer that can autonomously decompose product epics into actionable issues, estimate effort using historical velocity data, and balance sprints across team capacity.",
      "Linear AI connects to a team's code repository, pull request history, and issue completion data to build a model of individual developer velocity and task complexity. It uses this model to produce effort estimates that are calibrated to actual team performance rather than abstract story points.",
      "The sprint planning feature presents balanced sprint proposals with a confidence interval on completion probability, allowing engineering leads to accept or adjust the plan before committing. Early users report the tool reduces sprint planning meetings by 60–70%.",
      "Linear AI is available immediately on Pro and Enterprise plans. The company says it processed over 2 million planning suggestions during the private beta, with a 78% acceptance rate on generated issue breakdowns.",
    ],
    company: 'Linear',
    readTime: 4,
    tags: ['Linear', 'Project Management', 'AI', 'Developer Tools'],
  },
  {
    id: 16,
    category: 'Hardware',
    title: 'NVIDIA Unveils Blackwell Ultra: 288GB HBM4 GPU Designed for Trillion-Parameter Inference',
    excerpt: 'The next-gen H200 successor doubles memory bandwidth and introduces a dedicated LLM inference engine on-chip.',
    body: [
      "NVIDIA has unveiled the Blackwell Ultra GPU (B200 Ultra), the successor to the H200, featuring 288GB of HBM4 memory, 9.6 TB/s memory bandwidth, and a new on-chip LLM Inference Engine (LIE) that accelerates attention computation for long-context language models.",
      "The memory bandwidth improvement — 2.4× over the H200 — directly addresses the primary bottleneck in large language model inference: the speed at which weight matrices can be loaded from memory. NVIDIA claims the B200 Ultra achieves 4× higher tokens-per-second on 70B+ parameter models.",
      "The LLM Inference Engine is a dedicated hardware block implementing FlashAttention-3 directly in silicon, handling attention computation without utilizing the standard CUDA cores. This allows the GPU to run attention and linear layer computations in parallel for the first time.",
      "<blockquote>The B200 Ultra is not an evolution of the H200 — it's a purpose-built inference machine. We designed it around the specific bottlenecks of transformer inference at scale. — Jensen Huang, CEO, NVIDIA</blockquote>",
    ],
    company: 'NVIDIA',
    readTime: 4,
    tags: ['NVIDIA', 'GPU', 'Blackwell', 'AI Hardware'],
  },
  {
    id: 17,
    category: 'Research',
    title: 'Stanford CRFM Publishes HELM 2.0: New Holistic LLM Evaluation Framework',
    excerpt: 'The updated benchmark suite adds 60 new scenarios covering safety, robustness, and real-world task performance.',
    body: [
      "Stanford's Center for Research on Foundation Models (CRFM) has published HELM 2.0 (Holistic Evaluation of Language Models), a major expansion of its influential LLM evaluation framework that adds 60 new benchmark scenarios and introduces dedicated safety and robustness test suites.",
      "HELM 2.0 introduces four new evaluation dimensions not present in the original framework: adversarial robustness (performance under prompt injection), calibration (confidence alignment with accuracy), consistency (variance across semantically equivalent prompts), and efficiency (performance per dollar).",
      "The framework evaluates 42 publicly available and API-accessible models, including GPT-5 Turbo, Claude Sonnet 4.5, Gemini Ultra 2.0, Llama 4 70B, and Mistral Large 3. Results are presented across 200+ metrics with statistical confidence intervals.",
      "A notable finding: models that score highest on standard capability benchmarks do not consistently show the best safety or robustness characteristics — highlighting the importance of multi-dimensional evaluation for production deployment decisions.",
    ],
    company: 'Stanford University',
    readTime: 5,
    tags: ['HELM', 'Stanford', 'Evaluation', 'Benchmarks'],
  },
  {
    id: 18,
    category: 'Open Source',
    title: 'Deno 3.0 Launches with Built-In Package Manager and 100% Node.js Compatibility',
    excerpt: 'Deno achieves full compatibility with the Node.js ecosystem while shipping a faster, built-in dependency manager.',
    body: [
      "Deno 3.0 has launched with two headline features: complete Node.js and npm ecosystem compatibility, and `deno pkg` — a built-in package manager that replaces npm for Deno-first projects with significantly faster install times.",
      "Node.js compatibility is now described as '100%' by the Deno team, meaning any Node.js application can run on Deno without modification — including applications that depend on native Node.js addons (napi modules) which were previously unsupported.",
      "`deno pkg` uses a content-addressed local cache, parallel downloads, and a lockfile format that is deterministic across platforms. In benchmarks, it installs a typical monorepo dependency tree 3.8× faster than npm and 2.1× faster than pnpm.",
      "Deno 3.0 also ships a built-in key-value store (`Deno.openKv`) powered by SQLite on the local file system and FoundationDB in Deno Deploy — providing a zero-configuration persistence option for edge functions.",
      "<blockquote>Deno 3.0 is the version where the 'should I use Node or Deno' question goes away. You can use both — on the same codebase. — Ryan Dahl, creator of Node.js and Deno</blockquote>",
    ],
    company: 'Deno Land Inc.',
    readTime: 4,
    tags: ['Deno', 'JavaScript', 'Runtime', 'Open Source'],
  },
  {
    id: 19,
    category: 'Cloud',
    title: 'Cloudflare Workers Now Support WebAssembly Components and Full WASI Support',
    excerpt: 'Cloudflare\'s edge network gains the ability to run any WASM-compiled language natively at 300+ PoPs.',
    body: [
      "Cloudflare has announced full WebAssembly Component Model and WASI (WebAssembly System Interface) support on its Workers platform, enabling developers to deploy code compiled from any language with a WASM target — including Rust, Go, C++, Python, and Ruby — to Cloudflare's 300+ point-of-presence network.",
      "The Component Model support means developers can mix code from multiple languages within a single Worker application using standardized interface types, enabling polyglot edge applications without serialization overhead between language boundaries.",
      "WASI support provides Workers with a standardized system interface abstraction, including file system access (via in-memory virtual FS), sockets, and clock APIs — dramatically broadening the class of applications that can run on Cloudflare's edge.",
      "Existing Cloudflare Workers written in JavaScript and TypeScript are unaffected. WASM workers run in the same isolate-based sandbox and are subject to the same pricing model.",
    ],
    company: 'Cloudflare',
    readTime: 4,
    tags: ['Cloudflare', 'WebAssembly', 'WASI', 'Edge Computing'],
  },
  {
    id: 20,
    category: 'Dev Tools',
    title: 'Cursor 2.0 Launches with Autonomous Code Review and Cross-File Refactoring',
    excerpt: 'The AI-powered IDE evolves from autocomplete to agentic — capable of reviewing PRs and executing multi-file refactors.',
    body: [
      "Cursor has released version 2.0 of its AI-powered code editor, introducing two flagship agentic capabilities: autonomous code review and cross-file refactoring. These features mark a shift from Cursor's origins as an AI autocomplete tool toward a fully agentic development environment.",
      "The autonomous code review feature analyzes pull request diffs, identifies logic errors, security vulnerabilities, and performance anti-patterns, and posts review comments directly to GitHub — without requiring a human to open the PR.",
      "Cross-file refactoring allows developers to describe a structural change (e.g., 'extract this authentication logic into a dedicated service and update all callers') and have Cursor execute it across the entire repository, preserving behavior while applying the transformation.",
      "The refactoring engine uses a combination of tree-sitter AST analysis and LLM-based semantic understanding to ensure changes are syntactically correct and preserve the intended behavior. A test-run preview mode shows the diff before applying changes.",
      "<blockquote>We're not building a better autocomplete — we're building a collaborator. One that can handle the mechanical parts of engineering so humans can focus on the creative parts. — Michael Truell, CEO, Cursor</blockquote>",
    ],
    company: 'Anysphere (Cursor)',
    readTime: 5,
    tags: ['Cursor', 'AI IDE', 'Code Review', 'Developer Tools'],
  },
];

TC.timelineData = {
  2026: {
    June: { count: 20, topics: ['AI', 'Cybersecurity', 'Hardware', 'Open Source', 'Programming', 'Cloud', 'Research', 'Dev Tools'] },
  },
};

TC.activeDates = [1,2,3,5,6,7,8,9,10,12,13,14,15,16,17,19,20,21,22,23,24,26,27];
